version: 1.0.{build}
environment:
  CMAKE_GEN_TYPE: Visual Studio 14 2015
install:
- ps: >-
    choco install 7zip.commandline

    cd third_party

    Invoke-WebRequest  http://www.lua.org/ftp/lua-5.3.3.tar.gz -OutFile lua-5.3.3.tar.gz

    7z x lua-5.3.3.tar.gz

    7z x lua-5.3.3.tar

    cd ../

    git submodule update --init --recursive

    ./opencv_build.bat
cache: third_party/opencv/build
build_script:
- ps: >-
    cmake . -G $env:CMAKE_GEN_TYPE -DLOCAL_LUA_DIRECTORY="third_party/lua-5.3.3"

    cmake --build . --config Release
test_script:
- ps: ctest -C Release --output-on-failure